Feature
Krishnabot/Hello-Microverse pull request #1
Opened 2022-05-24 19:26 UTC by Krishnabot

2022-05-24 20:12 UTC, vechicin requested changes
# Hi @Krishnabot  ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- [x] Good commit history
- [x] Correct GitHub Flow use

## Required Changes ♻️

- [x] I suggest you change your PR title and add a description to it as they are part of the [project requirements](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md).
Here is what I suggest:
Title: Hello World
Description: In this feature I added a header with the text `Hello World` and styled it with my favorite color!
- [ ] Be very careful about pushing the `node_modules` directory. Due to the number of files in that directory, it may overload GitHub and make the reviewing process a nightmare for us code reviewers.
- [ ] I suggest you use Microverse's linters **exclusively,** you can find a step-by-step guide on how to install them [here](https://github.com/microverseinc/linters-config/blob/master/html-css/README.md). Please remove Stickler and the `lighthouseci` folder.

_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-24 20:12 UTC, vechicin commented on .gitignore
> +test.md
While the `test.md` file was correctly added to the `.gitignore` file, the `node_modules` directory was not. Kindly fix this as it is a project requirement.

You may want to research the following Git command: `git rm -r --cached`.

2022-05-24 20:12 UTC, vechicin commented on .stickler.yml
> +# find full documentation here: https://stickler-ci.com/docs
Kindly remove this linter, you need to use Microverse's linters without any additional ones.

2022-05-24 20:12 UTC, vechicin commented on README.md
There are a couple of tweaks in the README that I suggest you implement. In the `Project Name` header you need to type the project's name and in the `Description` section you need to type a description for the project.

2022-05-24 20:12 UTC, vechicin commented on README.md
> -### Deployment
I suggest you add the instructions on how to get a local copy of the project and how to install the required dependencies for it to run properly.

2022-05-24 20:15 UTC, vechicin commented
https://github.com/Krishnabot/Hello-Microverse/blob/0d67aa352201dd5cbf4cb284d8c80fdeb4ccbe9a/style.css#L1-L11
[OPTIONAL] Using color names is considered bad practice. I suggest you change these colors to their `rgb` or `hex` equivalents.

2022-05-24 21:48 UTC, vechicin commented on .gitignore
> +test.md
When installing Webhint and/or Stylelint or any other linter make sure you copy the `.github/workflows` directories into the project's root directory. After that execute the npm commands (I recommend you copy and paste them directly into your terminal from the README) and then copy the `hintrc` and `stylelintrc.json` files into the root directory as well. I hope this was useful.

2022-05-25 16:15 UTC, vechicin commented on .stickler.yml
> +# find full documentation here: https://stickler-ci.com/docs
@Krishnabot Hi, you need to submit another request through your dashboard, please.

2022-05-25 16:16 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
...
You used proper GitHub Flow ✔️
Your linter checks are passing ✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [ ] Please make sure you add the description of the PR in the first comment. You can click on the `...` at the top right corner of the comment and click on edit and then add a descriptive description of the PR.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-25 16:16 UTC, leonardodiasb commented on README.md
> +> Hello microverse
- [ ] Please add the Project Name as the title of the document and the description below it. You could change `# Project Name` to `# Hello Microverse` and add a description below it.

2022-05-25 16:44 UTC, topeogunleye approved these changes
### Hi @Krishnabot, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
> 
> ## [Optional] suggestions:
> * [ ]  Please kindly ensure all linters are passing.
![Screenshot from 2022-05-25 17-39-20](https://user-images.githubusercontent.com/52934128/170316706-1f14abf9-d3e1-4af5-9c2a-371c6cb68c33.png)
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-25 16:46 UTC, merged